# Generated by Django 5.0.3 on 2024-03-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publication_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publication_date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profiles/default.jpg', null=True, upload_to='images/profiles'),
        ),
    ]
